name: All

on: 
  pull_request:
    branches: [ main ]
  push: 
    tags: 
      - "*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build: 
    runs-on: ubuntu-latest
#    if: ${{ github.event.action }} == 'opened'
    steps:
    - uses: actions/checkout@v3
    - name: Build cmake
      run: | 
        sudo apt install ninja-build
        cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -GNinja
    
    - name: Build ninja
      run: |
        cd ${{github.workspace}}/build        
        ninja
        zip release.zip hello_actions
        cd ../scripts/
        ./teste.sh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          ${{github.workspace}}/build/release.zip
          ${{github.workspace}}/readme.zip

        
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - name: Get Tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        mv build/release.zip build/release_${{ env.RELEASE_VERSION }}_PROD.zip
    - name: Publish
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ env.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/release_${{ env.RELEASE_VERSION }}_PROD.zip
          readme.zip
