name: Release

on: 
  push: 
    tags: 
      - "v*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt install ninja-build
        cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -GNinja
        cd ${{github.workspace}}/build        
        ninja
        zip release.zip hello_actions
    
    - name: Publish
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ env.GITHUB_TOKEN }}"
        prerelease: false
        files: ${{github.workspace}}/build/release.zip

